/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'changelogs'.
 *      Allows anyone to see the changelogs of the bot.
 */

/*      IMPORTS      */
const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, MessageEmbed } = require( "discord.js" ); 
const pjson = require('../../../package.json');
const fs = require('fs');

 /*      AUTHORISATION      */
const { Changelogs } = require('../../files/modules.js');
 
 /* ----------------------------------------------- */
 /* COMMAND BUILD                                   */
 /* ----------------------------------------------- */
 const slashCommand = new SlashCommandBuilder()
     .setName( "changelogs" )
     .setDescription( "Affiche les récent changements de votre ami WTPBot." )
     .setDefaultPermission( true );
 
/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

const permissions = [
    {
        id: 'MOD_ID',
        type: 'ROLE',
        permission: true,
    },
];

 /* ----------------------------------------------- */
 /* FUNCTIONS                                       */
 /* ----------------------------------------------- */
 /**
  * Function called when the command 'ping'
  * @param {CommandInteraction} interaction The interaction generated by the command's execution.
  */
  async function execute( interaction ) {
    if(Changelogs == false) return;
    

    const messageContent = fs.readFileSync('./files/changelogs.txt', 'utf8')
    

    //EMBED
    // inside a command, event listener, etc.
    const embed = new MessageEmbed()
        .setColor('#e15dd9')
        .setTitle(`Changelogs v${pjson.version} :`)
        .setAuthor('WhatThePhoqueBot', interaction.client.user.avatarURL())
        .setDescription(messageContent)
        .setTimestamp(new Date())
        .setFooter('Merci à tous de nous soutenir ! :)', interaction.client.user.avatarURL())

        await interaction.reply(
            { embeds: [ embed ], ephemeral: false }
        );
}

 
 
 /* ----------------------------------------------- */
 /* MODULE EXPORTS                                  */
 /* ----------------------------------------------- */
 module.exports = {
    data: slashCommand,
    id: slashCommand.id,
    permissions: permissions,
    execute
 }
