/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'library'.
 *      Allows anyone to get a "Bibliothécaire"
 *      role to access to some archives.
 */

/*      IMPORTS      */
const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );
 
 /*      AUTHORISATION      */
const { Library } = require('../../files/modules.js');
 
 /* ----------------------------------------------- */
 /* COMMAND BUILD                                   */
 /* ----------------------------------------------- */
 const slashCommand = new SlashCommandBuilder()
     .setName( "library" )
     .setDescription( "Activer/Désactiver l'accès aux archives." )
     .setDefaultPermission( true );
 
/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

const permissions = [
    {
        id: 'MOD_ID',
        type: 'ROLE',
        permission: true,
    },
];

 /* ----------------------------------------------- */
 /* FUNCTIONS                                       */
 /* ----------------------------------------------- */
 /**
  * Function called when the command 'ping'
  * @param {CommandInteraction} interaction The interaction generated by the command's execution.
  */
  async function execute( interaction ) {
    if(Library == false) return;
    
    member = interaction.member
    let libraryRole = interaction.guild.roles.cache.get("916252819038830622"); //Certifié
    
    if(member.roles.cache.some(role => role.id === "916252819038830622")){
        member.roles.remove(libraryRole);
        await interaction.reply(
            { content: `Vous n'avez désormais plus accès aux archives !`, ephemeral: true }
        );
    }
    else {
        member.roles.add(libraryRole);
        await interaction.reply(
            { content: `Vous avez désormais accès aux archives !`, ephemeral: true }
        );
    }

     
 }
 
 
 /* ----------------------------------------------- */
 /* MODULE EXPORTS                                  */
 /* ----------------------------------------------- */
 module.exports = {
    data: slashCommand,
    permissions: permissions,
    execute
 }