/**
 * @author Benjamin Guirlet
 * @author Lothaire Guée
 * @description
 *      Handler for the command 'queue'.
 */


const { checkUserIsConnected } = require( "../../utils/voiceUtils" );

const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, Client, MessageEmbed } = require( "discord.js" );
const { Music } = require("../../files/modules");



const slashCommand = new SlashCommandBuilder()
	.setName( "m_queue" )
	.setDescription( "[music] Affiche les 10 premières musiques de la queue." );


/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

async function permissions(guild){
	const permissions = [
		{
			id: guild,
			type: 'ROLE',
			permission: true,
		},
	];
	return permissions;
}


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 */
async function execute( interaction ) {
	if(Music == false) return;
	if ( !(await checkUserIsConnected( interaction )) ) return;

	let client = interaction.client;

	const guildId = interaction.guildId;
	if ( client.guildsData.has( guildId ) ) {

		let textQueue = "";
		let totalLengthSeconds = 0;
		let cpt = 0;
		client.guildsData.get( guildId ).queue.forEach( (music) => {
			if ( cpt < 10 ) {
				textQueue += `**${cpt + 1}.** ${music.title} [${music.duration}]\n`;
			}
			totalLengthSeconds += music.lengthSeconds;
			++cpt;
		});

		const embedQueue = new MessageEmbed()
			.setColor( '#e15dd9' )
			.setAuthor( "┃ File d'attente", interaction.user.avatarURL() )
			.setDescription( textQueue === "" ? "File d'attente vide." : textQueue );

		if ( cpt !== 0 ) {
			embedQueue.setFooter( `${cpt} musique(s).` );
		}

		await interaction.reply( { embeds: [ embedQueue] } );
	}
	else {
		await interaction.reply({
			embeds: [
				new MessageEmbed()
					.setColor( '#e15dd9' )
					.setAuthor( "┃ Le bot n'est pas connecté à un vocal !", interaction.user.avatarURL() )
			]
		});
	}
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	permissions,
	execute
}