/**
 * @author Benjamin Guirlet
 * @file
 *		Handler for the shuffle command.
 */


 const { checkUserIsConnected } = require( "../../utils/voiceUtils" );

 const { SlashCommandBuilder } = require( "@discordjs/builders" );
 const { CommandInteraction, Client } = require( "discord.js" );
 
 
 const slashCommand = new SlashCommandBuilder()
     .setName( "m_shuffle" )
     .setDescription( "Mélange la queue" );
 


/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

async function permissions(guild){
	const permissions = [
		{
			id: guild,
			type: 'ROLE',
			permission: true,
		},
	];
	return permissions;
}
 
/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 */

async function execute( interaction ) {
    if ( !checkUserIsConnected( interaction ) ) return;

	let client = interaction.client;
    const guildId = interaction.guildId;
 
    if ( client.guildsData.get( guildId ).queue.length <= 1 )
        return interaction.reply( "Il n'y a pas assez de musiques dans la queue" );

    const queue = client.guildsData.get( guildId ).queue;
    const newQueue = [];
    let index;
    while ( queue.length != 0 ) {
        index = Math.floor( Math.random() * queue.length );
        newQueue.push( queue[index] );
        queue.splice( index, 1 );
    }

    client.guildsData.get( guildId ).queue = newQueue;

    await interaction.reply( "La queue a été mélangée!" );
}
 
 
 /* ----------------------------------------------- */
 /* MODULE EXPORTS                                  */
 /* ----------------------------------------------- */
module.exports = {
     data: slashCommand,
     permissions,
     execute
}