/**
 * @author Benjamin Guirlet
 * @author Lothaire Guée
 * @description
 *      Handler for the command 'time'.
 */


const { checkUserIsConnected, getIntDate } = require( "../../utils/voiceUtils" );

const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, Client, MessageEmbed } = require( "discord.js" );
const { Music } = require("../../files/modules");



const slashCommand = new SlashCommandBuilder()
	.setName( "m_time" )
	.setDescription( "[music] Affiche le temps restant avant la fin de la musique." );


/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

async function permissions(guild){
	const permissions = [
		{
			id: guild,
			type: 'ROLE',
			permission: true,
		},
	];
	return permissions;
}


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 */
async function execute( interaction ) {
	if(Music == false) return;
	if ( !(await checkUserIsConnected( interaction )) ) return;

	let client = interaction.client;

	const guildId = interaction.guildId;
	if ( client.guildsData.has( guildId ) ) {
		const guildData = client.guildsData.get( guildId );
		const remainingTimeSeconds = guildData.currentSong.lengthSeconds - (getIntDate() - guildData.currentSong.intDate);
		const remainingTime = `${Math.floor( remainingTimeSeconds / 60 )}m${remainingTimeSeconds % 60}s`;

		await interaction.reply( {
			embeds: [
				new MessageEmbed()
					.setColor( '#e15dd9' )
					.setAuthor( `┃ Il reste ${remainingTime} sur ${guildData.currentSong.duration} !`, interaction.user.avatarURL() )
					
			]
		});
	}
	else {
		await interaction.reply({
			embeds: [
				new MessageEmbed()
					.setColor( '#e15dd9' )
					.setAuthor( "┃ Le bot n'est pas connecté à un vocal !", interaction.user.avatarURL() )
			]
		});
	}
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	permissions,
	execute
}