/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'certify'.
 *      Allow mods to certify someone in the server.
 */

/*      IMPORTS      */
const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );
const { getSetupData } = require("../../utils/enmapUtils")
 
 /*      AUTHORISATION      */
const { Certify } = require('../../files/modules.js');
 
 /* ----------------------------------------------- */
 /* COMMAND BUILD                                   */
 /* ----------------------------------------------- */
 const slashCommand = new SlashCommandBuilder()
     .setName( "certify" )
     .setDescription( "Certifier une personne." )
     .setDefaultPermission( false )
     .addUserOption(option =>
        option.setName('user')
            .setDescription("Entrez l'utilisateur.")
            .setRequired(true));
 
/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

async function permissions(guild){
    const MOD_ID = await getSetupData(guild, "mod_id")
    const ADMIN_ID = await getSetupData(guild, "admin_id")
    const permissions = [
		{
			id: MOD_ID,
			type: 'ROLE',
			permission: true,
		},
        {
			id: ADMIN_ID,
			type: 'ROLE',
			permission: true,
		}
	];
	return permissions;
}

 /* ----------------------------------------------- */
 /* FUNCTIONS                                       */
 /* ----------------------------------------------- */
 /**
  * Function called when the command 'ping'
  * @param {CommandInteraction} interaction The interaction generated by the command's execution.
  */
  async function execute( interaction ) {
    if(Certify == false) return;
    const CERTIFY_ID = await getSetupData(interaction.guild.id, "certify")
    console.log(CERTIFY_ID)
    const NCERTIFY_ID = await getSetupData(interaction.guild.id, "ncertify")
    const DEMO_ID = await getSetupData(interaction.guild.id, "demo")

    member = interaction.options.getMember('user')

    let rolea = interaction.guild.roles.cache.get(CERTIFY_ID); //Certifié
    let roleb = interaction.guild.roles.cache.get(NCERTIFY_ID); //Non Certifié
    let rolec = interaction.guild.roles.cache.get(DEMO_ID); //Démo
    member.roles.add(rolea);
    member.roles.remove(roleb);
    member.roles.remove(rolec);

    await interaction.reply(
        { content: `Vous avez bien certifié <@${member.user.id}> !`, ephemeral: false }
    );
     
 }
 
 
 /* ----------------------------------------------- */
 /* MODULE EXPORTS                                  */
 /* ----------------------------------------------- */
 module.exports = {
    data: slashCommand,
    permissions: permissions,
    execute
 }