/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'audit'.
 *      Audit a user.
 */

const { SlashCommandBuilder } = require("@discordjs/builders");
const { MessageEmbed } = require("discord.js");
const JSONPenalties = require(`${process.cwd()}/files/sanctions.json`);

/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
    .setName("warnlist")
    .setDescription(
        "[mod] Obtenir les sanctions liées au /warn."
    )
    .setDefaultPermission(false);


    
/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */


/**
 * Function called when the command 'audit'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute(interaction) {
    
    const embedMessage = new MessageEmbed()
    .setTitle("Tous les warns (⬇️)")
    .setDescription("ℹ️ Sanctions attribués allant de bas en haut et de la forme (jour:heure:minute)")
    .setColor("#ffcc4d")

    for(let raison in JSONPenalties.enum){
        for (let sanction of JSONPenalties.sanctions) {
            for (let i = 0; i < sanction.reasons.length; i++) {
                if (sanction.reasons[i] === raison) {
                    let values = JSON.stringify(sanction.values)
                    values = values.replace("[", "")
                    values = values.replace("]", "")
                    values = values.replaceAll("\"", "")
                    values = values.replaceAll(",", "\n")
                    values = values.toUpperCase()
                    embedMessage.addField(`${JSONPenalties.enum[raison].emoji} ${JSONPenalties.enum[raison].name}`, values, true);
                }
            }
            
        }

    }

    interaction.reply({embeds:[embedMessage], ephemeral: true});
}

/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
    data: slashCommand,
    execute,
};
