/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'setup'.
 *      Allow admin to setup the JSON configuration file.
 */

/*      IMPORTS      */
const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );

const { setup, isSetupDone, getSetupData } = require("../../utils/enmapUtils")    

 /*      AUTHORISATION      */
const { Setup } = require('../../files/modules.js');
 
 /* ----------------------------------------------- */
 /* COMMAND BUILD                                   */
 /* ----------------------------------------------- */
 const slashCommand = new SlashCommandBuilder()
    .setName( "reset_setup" )
    .setDescription( "[setup] Supprimer les données de configuration du bot pour ce serveur." )
    .setDefaultPermission( false )
  
 /* ----------------------------------------------- */
 /* FUNCTIONS                                       */
 /* ----------------------------------------------- */
 /**
  * Function called when the command 'ping'
  * @param {CommandInteraction} interaction The interaction generated by the command's execution.
  */
  async function execute( interaction ) {
    if(Setup == false) return;

    setup.fetchEverything()
    setup.forEach( async (value, key) => {
        if(key === interaction.guild.id){
            setup.delete(key)
        }
    })

    isSetupDone.set(interaction.guild.id, false)

    await interaction.reply(
        { content: `Bot réinitialisé, si vous souhaitez le réutiliser, merci de démarrer /setup.`, ephemeral: true }
    );
     
 }
 
 
 /* ----------------------------------------------- */
 /* MODULE EXPORTS                                  */
 /* ----------------------------------------------- */
 module.exports = {
    data: slashCommand,
    execute
 }