/**
 * @author Lothaire Guée
 * @description
 *      Contains the command 'ping'.
 *      Pong the user.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction } = require( "discord.js" );

/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName( "ping" )
	.setDescription( "[bot] Donne la latence du bot et de l'API Discord en millisecondes." )
	.setDefaultPermission( false );

/* ----------------------------------------------- */
/* PERMISSIONS                                     */
/* ----------------------------------------------- */

async function permissions(guild){
	const permissions = [
		{
			id: guild,
			type: 'ROLE',
			permission: true,
		},
	];
	return permissions;
}

/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * Function called when the command 'ping'
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
 async function execute( interaction ) {
	await interaction.reply(
		{ content: `🏓 **PING**
		La latence du bot est de ${Date.now() - interaction.createdTimestamp}ms.
		Latence API Discord : ${Math.round(interaction.client.ws.ping)}ms`, ephemeral: false }
	);
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	permissions,
	execute
}