exports.ADVICES = [
    "UwUwUwUwUwUwUwU",
    "Lotharie aime beaucoup Sonic, Jet Set Radio et la French House.",
    "LaQuiche attend des investisseurs pour faire grandir son capital à l'aide d'une modération qualitative (fuck les rageux) en vue d'une ouverture permanente du serv minecraft #ripEternal",
    "Ered Luin te répondra, si de culture générale tu parleras !",
    "PozØr aurait apparement un très grand fétichisme pour les pieds, n'hésite surtout pas à les lui envoyer !",
    "Gay VIP: modeste,beaugosse,fort,gentil,extrêmement charismatique mais surtout il a un grand cœur",
    "Très discret et sympa et apparement il s'appelle ghost",
    "Aimer Monster Hunter vous accordera les faveurs de Dayamond",
    "Samourai.ytp vole vos memes, faites attention !",
    "Speedwagon adore la psychologie si vous voulez parler techniques de manipulation sur Youtube.",
    "De grâce, sors de chez toi et vas toucher de l'herbe et prends une douche.",
    "Tu peux gagner de l’XP en te rendant en vocal",
    "Chaque like que tu as reçu te rapporte de l’XP !",
    "Pour monter de niveau rapidement, il est préférable d’envoyer des memes jamais vu et drôle !",
    "Tu peux discuter avec la communauté dans ￼ !",
    "Tu peux donner ton avis sur les memes dans les commentaires, les auteurs des memes seront ravi de voir que l’on interagi avec leurs memes postés !",
    "Si tu n’aimes pas parler, ni poster, liker 10 memes t’apporte chaque jour un peu d’XP !",
    "Attention ! Ne poste pas de NSFW et d’humour noir sur le serveur sauf exception dans les salons prévus à cet effet !",
    "Ne postes pas des memes dans les mauvais salons ! Tu pourrais te faire descendre sur place public et perdre de l’XP à cause des réactions :recycle: que les gens te mettront…",
    "Sois sympa, ne fais pas de pub au sein du serveur et dans les messages privés des gens !",
    "Évitez d’entrainer des messages sur des sujets sensibles comme la politique.",
    "Si jamais tu as des questions sur ce que l’on doit respecter en tant que serveur Discord, tu peux consulter les règles officiel de Discord : lien pour Discord Community Guidelines",
    "Tu peux obtenir l’état de ton compte en tapant simplement la commande : /situation, elle te montrera tous tes warns.",
    "Si tu regardes bien ton /situation, l’embed change de couleur en fonction des warns. Attention à ne pas être dans le rouge !",
    "La couleur dans ton /situation est défini tous les 5 warns, si vous êtes au dessus de 10 (rouge), vous avez de grande chance de vous faire bannir. Prends garde à toi !",
    "Toutes les règles, fonctionnement, et autres astuces sont disponibles sur la [documentation](<https://docs.francememes.com>)",
    "Tu peux nous suivre sur les réseaux sociaux : [Twitter](<https://twitter.com/francememes_>), [Instagram](<https://instagram.com/francememes_>), [Reddit](<https://reddit.com/r/FRANCEMEMES_>) et [Tiktok](<https://tiktok.com/@francememes_>)",
    "OwO Si vous avez des nekopics en trop *nyaa~~* N'hésitez pas a venir voir Asaka en privé UwU (ou si vous en voulez >///< ). A bientôt les loulous *nyaa~* je vous lèche la patoune OwO",
];
