exports.ADVICES = [
    "UwUwUwUwUwUwUwU",
    "Lotharie aime beaucoup Sonic, Jet Set Radio et la French House.",
    "LaQuiche attend des investisseurs pour faire grandir son capital à l'aide d'une modération qualitative (fuck les rageux) en vue d'une ouverture permanente du serv minecraft #ripEternal",
    "Ered Luin te répondra, si de culture générale tu parleras !",
    "PozØr aurait apparement un très grand fétichisme pour les pieds, n'hésite surtout pas à les lui envoyer !",
    "Gay VIP: modeste, beau gosse, fort, gentil, extrêmement charismatique mais surtout il a un grand cœur",
    "Très discret et sympa et apparement il s'appelle Ghost",
    "Aimer Monster Hunter vous accordera les faveurs de Dayamond",
    "Samourai.ytp vole vos memes, faites attention !",
    "Speedwagon adore la psychologie si vous voulez parler techniques de manipulation sur Youtube.",
    "De grâce, sors de chez toi, va toucher de l'herbe et prends une douche.",
    "Tu peux gagner de l’XP en te rendant en vocal",
    "Chaque like que tu as reçu te rapporte de l’XP !",
    "Pour monter de niveau rapidement, il est préférable d’envoyer des memes jamais vus et drôles !",
    "Tu peux discuter avec la communauté dans ￼ !",
    "Tu peux donner ton avis sur les memes dans les commentaires, les auteurs des memes seront ravis de voir que l’on interagit avec leurs memes postés !",
    "Si tu n’aimes pas parler, ni poster, liker 10 memes t’apporte chaque jour un peu d’XP !",
    "Attention ! Ne poste pas de NSFW et d’humour noir sur le serveur sauf exception dans les salons prévus à cet effet !",
    "Ne poste pas des memes dans les mauvais salons ! Tu risques de te faire pincer très fort",
    "Si tu veux perdre de l’XP, repostes un meme déjà posté et profites des :recycle: que les gens te mettront…",
    "Sois sympa, ne fais pas de pub au sein du serveur et dans les messages privés des gens !",
    "Évite de poster des messages sur des sujets sensibles comme la politique ou de lancer des débats.",
    "Si jamais tu as des questions sur ce que l’on doit respecter en tant que serveur Discord, tu peux consulter les règles officiel de Discord : https://discord.com/guidelines",
    "Tu peux obtenir l’état de ton compte en tapant simplement la commande : /situation, elle te montrera tous tes warns.",
    "Si tu regardes bien ton /situation, l’embed change de couleur en fonction des warns. Attention à ne pas être dans le rouge !",
    "La couleur dans ton /situation est défini tous les 5 warns, si vous êtes au dessus de 10 (rouge), tu as de grandes chances de te faire bannir. Prends garde à toi !",
    "Toutes les règles, fonctionnement, et autres astuces sont disponibles sur la [documentation](<https://docs.francememes.com>)",
    "Tu peux nous suivre sur les réseaux sociaux : [Twitter](<https://twitter.com/francememes_>), [Instagram](<https://instagram.com/francememes_>), [Reddit](<https://reddit.com/r/FRANCEMEMES_>) et [Tiktok](<https://tiktok.com/@francememes_>)",
    "OwO Si vous avez des nekopics en trop *nyaa~~* N'hésitez pas a venir voir <@684413418006249472> en privé UwU (ou si vous en voulez >///< ). A bientôt les loulous *nyaa~* je vous lèche la patoune OwO",
    "Tu cherches la baston sale chien ? Vas-y essaye de me /fumer pour voir, sale merde. Je te défonce.",
];
