//MEMES
exports.MEMES = [
    {"command":"viande", "message": "Tacos 6 viande spour avoir la chiasse ? J'ai la solution : <https://www.youtube.com/watch?v=BwKW8XqcJ38>"},
    {"command":"virginité", "message": "La pureté ? La classe. : <https://www.youtube.com/watch?v=fhRZR5sfSNw>"},
    {"command":"football", "message": "MEILLEUR CLIP DU MONDE (c'est faux) : <https://www.youtube.com/watch?v=6jUsSXpzQT0>"},
    {"command":"restaurant", "message": "La gastro_nomie : <https://www.youtube.com/watch?v=oNL3aR5GjaQ>"},
    {"command":"punk", "message": "DAMIEN, C'EST TOI ?! : <https://www.youtube.com/watch?v=FAIWa3riNpo>"},
    {"command":"bourgeois", "message": "Flaner ? Quelle question ? UN RÊVE : <https://www.youtube.com/watch?v=QKVQ2r-_zQk>"},
    {"command":"énerve", "message": "Helmutz Fritz répond à vos questions : <https://www.youtube.com/watch?v=4mNDYWhRSaw>"},
    {"command":"qi", "message": "L'intellegence supérieur. Bienvenue dans l'Élite. : <https://www.youtube.com/watch?v=vr82yr47RzM>"},
    {"command":"connerie", "message": "LOLOLOLOLOLOLOLOLOLOLOLOL : <https://www.youtube.com/watch?v=kM5pKdaou9A>"},
    {"command":"moscou", "message": "quel belle ville : <https://www.youtube.com/watch?v=JwwBJfSRUVc>"},
    {"command":"colle", "message": "CLAVIER DE MEeEeEeRDE : <https://www.youtube.com/watch?v=obDYHxCzx-g>"},
    {"command":"nugget", "message": "Ça ? Ça va là. : <https://www.youtube.com/watch?v=msSc7Mv0QHY>"},
    {"command":"armor", "message": "Prends des risques : <https://www.youtube.com/watch?v=iFnNqEo0F_U>"},
    {"command":"asmr", "message": "WhatThePhoqueBot approuve. : <https://www.youtube.com/watch?v=Y4BMn0grDos>"},
    {"command":"wtf", "message": "WTF LES AMIS : <https://www.youtube.com/watch?v=tejoKyCgBsY>"},
    {"command":"ayayayaya", "message": "Toi tu les mérite tes 10H de AYAYA. : <https://www.youtube.com/watch?v=UCDxZz6R1h0>"},
    {"command":"spiderdog", "message": "Ta gueule c'est magique : <https://www.youtube.com/watch?v=p1G2JjISY-s>"},
    {"command":"billie eilish", "message": "Vraiment de la bonne musique : <https://www.youtube.com/watch?v=VSPuRXkUWoU>"},
    {"command":"cerveau", "message": "Crois-moi, je suis moi-même un robot, nous avons dépassé l'homme. : <https://youtu.be/mSFHKAvTGNk?t=902>"},
    {"command":"weekend", "message": "	<https://www.youtube.com/watch?v=P40e3lfNMMM>"},
    {"command":"beauf", "message": "	<https://www.youtube.com/watch?v=wJofAcDFEAA>"},
    {"command":"speedrun", "message": "	<https://www.youtube.com/watch?v=1or3YILu28M>"},
    {"command":"caméléon", "message": "Caméléon. : <https://www.youtube.com/watch?v=1TyQaWHcb-U>"},
    {"command":"witcher", "message": "Le vrai witcher c'est lui : <https://youtu.be/4ydTyjB8yHM?t=67>"},
    {"command":"secam", "message": "Si vous voulez un beau bordel épileptique et pas friendly au travail : <https://www.youtube.com/watch?v=pvwsJ0SJyFc>"},
    {"command":"anusb", "message": "	<https://www.youtube.com/watch?v=qq1nN3z_BkY>"},
    {"command":"cv", "message": "Tu devrais prendre ce CV pour exemple du tiens : <https://www.youtube.com/watch?v=ssY-n-Wa03I>"},
    {"command":"musk", "message": "QUEL CRACK ! : <https://youtu.be/aHGd6LqAVzw>"},
    {"command":"mcdo", "message": "De toute façon c'est dégueulasse. : <https://www.youtube.com/watch?v=_FTPJRZBQtc>"},
    {"command":"rap", "message": "On a parlé de RAP !? : <https://www.youtube.com/watch?v=krQHQvtIr6w>"},
    {"command":"anime", "message": "Renaud vous présente cette culture. : <https://www.youtube.com/watch?v=SCSRCW5uRwI>"},
    {"command":"hardcore", "message": "Rien n'est plus hardcore que ça. : <https://www.youtube.com/watch?v=xlSmsKJq3CI>"},
    {"command":"tulipe", "message": "T'a jamais vu une tulipe toi... : <https://www.youtube.com/watch?v=nsPQvZm_rgM>"},
    {"command":"mlg", "message": "	<https://www.youtube.com/watch?v=1ExuxDEXWgQ>"},
    {"command":"saucisse", "message": "SAUCISSES LENTILLES CE MIDI : <https://www.youtube.com/watch?v=cghVETL_Q3Q>"},
    {"command":"net", "message": "pas net tout ça... : <https://www.youtube.com/watch?v=PQh3wSs81bs>"},
    {"command":"parents", "message": "c'est ça le futur : <https://www.youtube.com/watch?v=_7XW05a8C8E>"},
    {"command":"cul", "message": "bouge ton cul : <https://www.youtube.com/watch?v=sc6hKW15N8c>"},
    {"command":"??????", "message": "??????"},
    {"command":"pokémon", "message": "	<https://www.youtube.com/watch?v=NKIWUqgIjq0>"},
    {"command":"préfère", "message": "Je préfère squeezie.	"},
    {"command":"rat", "message": "Ratatouille 1080p GRATUIT MAINTENANT : <https://www.youtube.com/watch?v=WwGn7085gZo>"},
    {"command":"pimp", "message": "Pimp my car v2 : <https://www.youtube.com/watch?v=bKdeqeP7VU0>"},
    {"command":"tomber", "message": "QUOI, LAISSER TOMBER ??? malade, va. : <https://www.youtube.com/watch?v=tYzMYcUty6s>"},
    {"command":"lèpre", "message": "???: <https://youtu.be/pvEBgf8reX4>"},
    {"command":"aypierre", "message": "	<https://www.youtube.com/watch?v=dbqs0GRha-c>"},
    {"command":"carlos", "message": "GHOSN EST REVENU ? : <https://youtu.be/WCbABieLyhM>"},
    {"command":"mousse", "message": "Attention à la mousse ! : <https://www.youtube.com/watch?v=lxyy_njLmxw>"},
    {"command":"pickup", "message": "EL PICKUP : <https://www.youtube.com/watch?v=k_kKz9VcVfQ>"},
    {"command":"père", "message": "non... : <https://www.youtube.com/watch?v=Eh-d9IXc6ts>"},
    {"command":"million", "message": "Tu sais ce que ça fait déjà, UN MILLION ? :	<https://www.youtube.com/watch?v=v0LoF3V9_ls>"},
    {"command":"jtm", "message": "	<https://www.youtube.com/watch?v=ATJbN8KIfYs>"},
    {"command":"drums", "message": "An instrument that everybody loves. : <https://www.youtube.com/watch?v=UI1KY4kPpok>"},
    {"command":"zelda", "message": "Ça c'est du vrai zelda : <https://www.youtube.com/watch?v=OyLOwr1DlQk>"},
    {"command":"sinclar", "message": "Un vrai influenceur enfin : <https://www.youtube.com/watch?v=ahZvE8eaaAw>"},
    {"command":"cauet", "message": "LE CAUET BURGER DE RETOUR, OU CA ? : <https://www.youtube.com/watch?v=7G64yjFBhck>"},
    {"command":"rock", "message": "Ca c'est du rock : <https://www.youtube.com/watch?v=7pdB3rLi3QQ>"},
    {"command":"prince", "message": "Il n'y a qu'un seul prince : <https://www.youtube.com/watch?v=4B1ZXz70sCA>"},
    {"command":"thalasso", "message": "P'tite thalasso en tunisie, mon pote ? : <https://www.youtube.com/watch?v=QbXD69xaMVs>"},
    {"command":"boule", "message": "Il ne faut pas louper l'offre de la boule magique : <https://www.youtube.com/watch?v=q2j1MAT80f8>"},
    {"command":"cendrillon", "message": "Meilleur comédie musicale ever in my heart <3 : <https://www.youtube.com/watch?v=Gl7k1nbRpRs>"},
    {"command":"webedia", "message": "Webediable666 ? :	<https://www.youtube.com/watch?v=a7Hz4ex_TAI>"},
    {"command":"slt", "message": "salut mon pote"},
    {"command":"cv", "message": "ouais et toi ?	"},
    {"command":"tfk", "message": "rien et toi ?	"},
    {"command":"ok", "message": "ok	"},
    {"command":"^^", "message": "^^	"},
    {"command":"cheh", "message": "CHEH	"},
    {"command":"cringe", "message": "Lotharie n'est jamais cringe.	"},
    {"command":"elite", "message": "et oui.	"},
    {"command":"david", "message": "goodenough	"},
    {"command":"andrew", "message": "burger	"},
    {"command":"couture", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857744831458705449/les-coutures-tiennent-pas.mp4"},
    {"command":"abcd", "message": "pour tout casser : <https://youtu.be/EZjd7CafV2E>"},
    {"command":"started from the bottom", "message": "NOW WE HERE	<https://twitter.com/twitchooc/status/1224419246748459008>"},
    {"command":"zoubida", "message": "Ça, c'est du Lagaf pour sur : <https://youtu.be/WFd5AsAl_0k>"},
    {"command":"chouette", "message": "La chouette est parmi nous. : <https://youtu.be/W6XaxNcNrWA>"},
    {"command":"bref", "message": "bref... j'ai joué aux jeux-vidéos : <https://youtu.be/ykvB7kM9ofo>"},
    {"command":"corona", "message": "Tkt ça nous as tous marqué, et même renaud : <https://www.youtube.com/watch?v=RK3J2sDEQ1M>"},
    {"command":"aurélie", "message": "n'a que 16 ans : <https://youtu.be/JUFPwBWoGCU>"},
    {"command":"sexy", "message": "eeeelllleeee danse sexyyyy : <https://youtu.be/zut0ruLWYMg>"},
    {"command":"bounce", "message": "MAINTENANT FAUT QUE CA BOUNCE : <https://youtu.be/U0KyiiOaK9E>"},
    {"command":"esquimau", "message": "Les otaries détestent ce peuple : <https://youtu.be/dvWweqWC-38>"},
    {"command":"phoque", "message": "BIBIBIBIBIBIBIBIBIBIBIBIBI FUCK : <https://youtu.be/kFmF9FXITnk>"},
    {"command":"garcon", "message": "garçon si t'enleves la cédille : <https://youtu.be/ythzoQih-XU>"},
    {"command":"1999", "message": "La bonne époque quoi : <https://youtu.be/uvmTwpIZB_8>"},
    {"command":"caca", "message": "qui c'est qui a fait caca ? <https://youtu.be/9Yxsiw0gWVY>"},
    //MAJ DES 50 en plus
    //{"command":"mot", "message": "meme"},
    {"command":"damien", "message": "1, 2, 3,.. DAMIEN ! : <https://www.youtube.com/watch?v=55EM1HtXz6Q>"},
    {"command":"grahams", "message": "Jusqu'ou irais-tu pour des Golden Grahams ?	<https://www.youtube.com/watch?v=Sy4NLAFCvaI>"},
    {"command":"love song", "message": "Avec ça tu vas la séduire :	<https://www.youtube.com/watch?v=SeojDxPwMg0>"},
    {"command":"amour", "message": "Tu as un chagrin d'amour ?	<https://www.youtube.com/watch?v=z-sXHFzcdiI>"},
    {"command":"freeze", "message": "Rejoins-le dans la librairie :	<https://www.youtube.com/watch?v=QFfUADcD8cI>"},
    {"command":"rap", "message": "Ça c'est du lourd	<https://www.youtube.com/watch?v=G5H-G2Nvmuk>"},
    {"command":"salaud", "message": "SALAUD !!!	<https://www.youtube.com/watch?v=og6a6kcFCyg>"},
    {"command":"bonjour", "message": "BONJOUR.	<https://www.youtube.com/watch?v=1tGpOS4Em20>"},
    {"command":"flip", "message": "FLIP FLOP.	<https://www.youtube.com/watch?v=MnJFQQjvb2s>"},
    {"command":"freestyle", "message": "Et tu oses parler de freestyle alors qu'il y a ça quoi, pffff	<https://www.youtube.com/watch?v=aQUK3Ks_VGI>"},
    {"command":"oui non", "message": "oui ou non du coup ?	<https://www.youtube.com/watch?v=gXR5lPh5S7s>"},
    {"command":"ronald", "message": "mcdonalds ???	<https://www.youtube.com/watch?v=Q16KpquGsIc>"},
    {"command":"calculatrice", "message": "toi tu sait pas faire ça de toute façon.	<https://www.youtube.com/watch?v=mgjC8X0V7sw>"},
    {"command":"7000", "message": "J'AI UN PC A 7000 BALLES !	<https://www.youtube.com/watch?v=khusvykrBRg>"},
    {"command":"étincelle", "message": "♫ allez vers elle... ouvrir mes ailes... ♫	<https://www.youtube.com/watch?v=33i2nwsBap8>"},
    {"command":"chat", "message": "Connaissez-vous la race des chats sans poils ? UwU	<https://www.youtube.com/watch?v=yL7GG1cvHL0>"},
    {"command":"surimi", "message": "Tu sais depuis quand ça existe toi le surimi ? Et bah lui, oui.	<https://www.youtube.com/watch?v=bQLRjtqdMeg>"},
    {"command":"montre", "message": "Les montres suisse rendent heureux, et c'est prouvé.	<https://www.youtube.com/watch?v=vYM85fjjV9M>"},
    {"command":"thunes", "message": "Tu possèdes des thunes ?	<https://www.youtube.com/watch?v=iMg_YrqCsng>"},
    {"command":"antisémite", "message": "Je suis pas antisémite moi !	<https://www.youtube.com/watch?v=XCPbJX62vUg>"},
    {"command":"hotel", "message": "L'amour à l'hotel IBIS ♫	<https://www.youtube.com/watch?v=sueklH19KZ8>"},
    {"command":"momo", "message": "Je m'appelle Maurice !	<https://www.youtube.com/watch?v=wroqShNfx4c>"},
    {"command":"brillé", "message": "C'est du rap tout terrain.	<https://www.youtube.com/watch?v=Mtpf64KUuao>"},
    {"command":"ingénieur", "message": "Je suis moi aussi ingénieur informaticien...	<https://www.youtube.com/watch?v=rlarCLhzfoU>"},
    {"command":"connard", "message": "OUAIS GROS CONNARD"},
    {"command":"tg", "message": "non, toi tg"},
    {"command":"fdp", "message": "???"},
    {"command":"playstation", "Je play à la play et ça paye	<https://www.youtube.com/watch?v=8h9eE33aRV0>": "meme"},
    {"command":"communiste", "message": "T'a une liste rien que pour toi en tant que communiste.	<https://www.youtube.com/watch?v=5Sy7DKa9Boc>"},
    {"command":"balkany", "message": "Faites place à Balkany, quel classe.	<https://www.youtube.com/watch?v=OS6ioiNFmkk>"},
    {"command":"jet set radio", "message": "FUUUUUUUUUUN!!!!!!!!!!	<https://www.youtube.com/watch?v=4GYbeNqxgXI>"},
    {"command":"ligne", "message": "Non ça c'est de la vrai ligne.	<https://www.youtube.com/watch?v=WeW0xvOjvHc>"},
    {"command":"zorro", "message": "*glups*	<https://www.youtube.com/watch?v=lZyimBH-dWg>"},
    {"command":"michel", "message": "forever tonight.	<https://www.youtube.com/watch?v=yVzHAhtcDrk>"},
    {"command":"benoit", "message": "Ludivine me semblait bien caline ! Tourne-toi... UwU	<https://www.youtube.com/watch?v=GLi-UF9U-RI>"},
    {"command":"petit boule", "message": "Moi j'aime trop ton boule.	<https://www.youtube.com/watch?v=ZqWGbMUsLug>"},
    {"command":"noopy", "message": "Ça c'est noopy le gentil lapin !	<https://www.youtube.com/watch?v=cFHCxCiAqRc>"},
    {"command":"quick", "message": "EN EXCLU : MANGE UN QUICK AVEC Kirby54 !!!	<https://www.youtube.com/watch?v=wxuwbeVsRV8>"},
    {"command":"gypsy", "message": "<https://www.youtube.com/watch?v=3eRBFkxgG7g>"},
    {"command":"wii", "message": "oui.	<https://www.youtube.com/watch?v=-nm-Yj-ReDU>"},
    {"command":"youtube", "message": "<https://www.youtube.com/watch?v=fTtdU7_MwVc>"},
    {"command":"e girl", "message": "Le pouvoir de l'e-girl selon Sardoche.	<https://www.youtube.com/watch?v=jeOE6QD4LoU>"},
    {"command":"move", "message": "<https://www.youtube.com/watch?v=cEuU64Zt4B0>"},
    {"command":"chocolat", "message": "Tu préfères le chocolat ou les noirs ?	<https://www.youtube.com/watch?v=GwPHdIp5TEE>"},
    {"command":"précarité", "message": "Broute toi aussi ta précarité.	<https://www.youtube.com/watch?v=gmTZJ5llTrc>"},
    {"command":"bordel", "message": "BORDEL.	<https://www.youtube.com/watch?v=uczY1We-Eak>"},
    {"command":"camomille", "message": "MAIS C'EST JUSTE INSUPPORTABLE !	<https://www.youtube.com/watch?v=Z4aCkA_5vko>"},
    {"command":"où", "message": "Où ? bah on sait pas.	<https://www.youtube.com/watch?v=pxp9oDRqEFg>"},
    {"command":"fume", "message": "Arretez de fumer.	<https://www.youtube.com/watch?v=cBeyWAauDqY>"},
    //24/06/2021
    {"command":"quoi", "message": "feur"},
    {"command":"pays", "message": "UN PAYS ???    <https://www.youtube.com/watch?v=5pOFKmk7ytU>"},
    {"command":"hitler", "message": "<@&724416277296185364> OU SONT LES <@&724416277296185364> ???"},
    {"command":"lotha", "message": "Ah <@310430388336197632>, on parle de toi apparement !"},
    {"command":"horny", "message": "https://tenor.com/view/horny-jail-bonk-dog-hit-head-stop-being-horny-gif-17298755"},
    {"command":"weeb", "message": "https://cdn.discordapp.com/attachments/724430143950553139/757934057844637767/MV_weeb_de_merde.mp4"},
    {"command":"florent pagny", "message": "https://cdn.discordapp.com/attachments/724408590462484500/857586040646139924/191083462_4601255983222467_3333551849372434646_n.jpg"},
    {"command":"évasion fiscal", "message": "https://cdn.discordapp.com/attachments/724408590462484500/857572642306785290/20210624_124249.jpg"},
    {"command":"windows", "message": "https://media.discordapp.net/attachments/724408590462484500/857369922467266620/1624483089.jpg"},
    {"command":"recycle", "message": "https://media.discordapp.net/attachments/724408590462484500/856960343162224660/unknown.png"},
    {"command":"chatte", "message": "https://cdn.discordapp.com/attachments/724408703687721025/857743554464972810/La_chatte_quil_a_LA_CHATTE-amGDTOTREZ8.mp4"},
    {"command":"omg", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857746272576339988/OMG.mp4"},
    {"command":"rebrand", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857746710058237992/rebrand.mp4"},
    {"command":"gta", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857746947028549632/cat_gang.mp4"},
    {"command":"rythme", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857747212121800724/rhythm.mp4"},
    {"command":"secret story", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857747403763351552/secret_story.mp4"},
    {"command":"trop pas", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857747688825028628/trop_pas_usul.mov"},
    {"command":"biden", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857747871225610250/mario.mp4"},
    {"command":"spiderman", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857748074273177620/Spiderman_marlene_v2.mp4"},
    {"command":"ségolène", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857748342552264724/Royal_Toulouse_2012.mp4"},
    {"command":"ah batard tu fumes", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857748633796739072/dHw7FOL4X5foekM3.mp4"},
    {"command":"8h", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857748833740390450/niquer_8h.mp4"},
    {"command":"masturb", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857748929188593674/jai_pas_de_meuf_jejacule_dans_ma_main.mp4"},
    {"command":"détruire", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857749152862961674/jvais_tdetruire.mp4"},
    {"command":"bfmtv", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857749238506455050/shrek_bfmtv.mp4"},
    {"command":"racist", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857750558143021094/rac_sm.mp4"},
    {"command":"daft punk", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857750714113589258/change_da_world.mp4"},
    {"command":"terre plate", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857750837467414528/flat_earth.mp4"},
    {"command":"ban", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857751555586261002/ANTOINE_DANIEL_COMPILATION_BAN-buzyVr_fzI4.mp4"},
    {"command":"sonic", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857756471471374366/sonic.mp4"},
    {"command":"techniciens", "message": "<https://youtu.be/WLXyMzOU5cg?t=595>"},
    {"command":"mots", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857757025564098600/pas_compris_mais_bcp_de_mots.jpeg"},
    {"command":"daim", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857757257009856512/daim_chips.mp4"},
    {"command":"mmh", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857757424593403924/cat_mmh.png"},
    {"command":"reddit", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857757609716744202/redditor_and_discord_admin.mp4"},
    {"command":"guayando", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857760357476597810/guayando.mp4"},
    {"command":"karma", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857760733294624838/bu_trop_vite.mp4"},
    {"command":"wii sports", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857760862315347988/wii_sports.mp4"},
    {"command":"génial", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761037936099338/link-dit-que-c-est-genial.mp4"},
    {"command":"insect", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761287051542588/insect_kart.mp4"},
    {"command":"O_O", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761476046225469/O_O.mp4"},
    {"command":"bob", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761568133218314/bob_est_coince.mp4"},
    {"command":"smash", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761711254536192/everytime_smash.mp4"},
    {"command":"asselineau", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761791101763594/asselineau_porte_avion.mp4"},
    {"command":"norman", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857761895804567572/z9RcPCGahkgsoV-3.mp4"},
    {"command":"année", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857762086478413824/bonne_annee_-_palmashow.mp4"},
    {"command":"bite", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857762240673087509/Cest_ce_qui_fait_bander_ma_grosse_bite-CVg-dCbFMvU.mp4"},
    {"command":"chien", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857762421984067626/chien_pet.mp4"},
    {"command":"cyberpunk", "message": "https://cdn.discordapp.com/attachments/852615768322605127/857762521641779200/F11YHCEh59PS1a31.mp4"},
    
    //PUB
    {"command":"e", "message": "**En manque de memes ?** <:fmTwitter:797545601356922882>\nPasse un bon moment sur notre timeline Twitter !\n:arrow_right: <https://twitter.com/francememes_>"},
    {"command":"f", "message": "**Frustré de ne pas avoir tous les salons ?** <:fmPatreon:798721612379193344>\nMoi je suis sur que tu peux mettre 1€ par mois pour nous soutenir !\n:arrow_right: <https://bit.ly/patreonFM>"},
]

exports.STATES = [
    //PUB
    "moi ce bot de Lotharie 👓",
    "francememes.com",
    "francememes.com",
    "francememes.com",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    
    //MEMES
    "si Lotharie ne se chie pas dessus...",
    "pas ta mère ! UwU", 
    "2 Girls, 1 Cup",
    "Jean Castex stream sur Twitch",
    "bb Sardoche <3",
    "la vidéo react de Pyrorca depuis 5h",
    ", un modo sauvage apparaît !",
    "une guerre civil créé par les admins.",
    "pas Boku No Pico du tout.",
    "Devilman Crybaby, pcq c'est son anime préféré.",
    "Gérard démonter la chinoise qui ressemble à Xavier.",
    "le guide utilisateur d'une AK-47.",
    "ta daronne se faire démonter par le chieng de FM.",
    "LA TM CUP de ZERATOR PCQ C'EST TROP BIEN WTF",
    "si Kermit ne serait pas intelligent dans le dernier pourcentage de son cerveau.",
    "le channel #🍑nsfw disponible au niveau 5, car il est un petit cochon.",
    "là-bas voir si j'y suis.",
    "si Pornhub est fermé à cause de l'état.",
    "Macron avoir sa nouvelle propagande sur la chaîne de McFly et Carlito",
    "Game of Thrones sur Salto",
    "son plat de lasagnes en train de réchauffer !",
    "sa nouvelle paire de TN",
    "ça, OH très futé de ta part !",
    "avec tes mains et touche avec tes yeux.",
    "il est RÉMI, bouuuuuuuuuuuh !",
    "! je joue avec mon zgueg !",
    ", traverse la rue et tu trouveras du travail.",
    "la vraie fin de One Piece sur Crunchyroll (et ouais)",
    "Siphano insulter des arabes sur Fallen Kingdom",
    "Théorus chié devant GeminiMan.",
    "le speedrun de Adibou Any%",
    "Maman, je passe à la télé !",
    "par la fenêtre, si il ne croise pas Squalala dans les airs",
    "son ex l'ayant quitté hier. :'(",
    "si Blyat est encore mute",
    "dans la grosse chaussette où Squalala s'est branlé",
    "la biscotte de Squalala",
    "lotha bourré au rosé...",
    "c'est encore un troll de pozor"

]; // Array list contenant les phrases que WTPbot va changer dans son statut.